version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Algotec
  - Algotech
  - Carestream
  - CODALLEH
  - Colour
  - corehard
  - cppcon
  - cpponsea
  - CPPP
  - cyberark
  - Cybereason
  - CYBR
  - Cymotive
  - Cynet
  - Eurovision
  - Eyeway
  - Firebolt
  - Harman
  - hyperscale
  - includecpp
  - Incredibuild
  - INFINIDAT
  - Istra
  - jetbrains
  - Kistler
  - lighbits
  - Lightbits
  - LOGOEYEWAY
  - mobileye
  - Packt
  - permissionless
  - Speedata
  - stressless
  - Thinkcell
  - Vayyar
  - aarch
  - Akram
  - Alisdair
  - Alphapulse
  - ASan
  - Axxana
  - Bagdonas
  - Binutils
  - Cephalocon
  - Comverse
  - Coobeeyon
  - CppNorth
  - CRTP
  - CTAD
  - Darebiz
  - Dathskovsky
  - Elbit
  - Eliaz
  - godbolt
  - Khlebnikov
  - Kirsh
  - Kivity
  - Kushnir
  - Lakos
  - libgcc
  - Lifshitz
  - lockfree
  - Matia
  - MedTech
  - MESI
  - MicroVMs
  - mpmc
  - Nassi
  - Nathanel
  - newlib
  - Niro
  - NRGene
  - Perelman
  - printk
  - QEMU
  - RCU
  - Regev
  - Romanov
  - Rostislav
  - Saksham
  - ScyllaDB
  - Seastar
  - SFINAE
  - Shabi
  - Shavit
  - Shemesh
  - Shilon
  - Simerda
  - Šimerda
  - Technion
  - TSan
  - Twistlock
  - UBSan
  - Valgrind
  - Verilog
  - Vittorio
  - Yacobi
  - Yaffo
  - Zoabi
ignoreWords: []
import: []
